#include <libcc/snowflake.h>
#include <libcc/time.h>
#include <libcc/logger.h>
/**
 * ID Generation Strategy
 * 41-bit millisecond timestamp + 10-bit machine ID + 12-bit millisecond sequence. High bit is always 0, indicating positive number.
 * 0           41     51     64
 * +-----------+------+------+
 * |time       |pc    |inc   |
 * +-----------+------+------+
 *  The first 41 bits are timestamp in microseconds.
 *  The next 10 bits are pre-configured machine ID.
 *  The last 12 bits are incremental counter.
 *  machine id (10bits) indicates maximum of 1024 machines can generate IDs simultaneously,
 *  sequence number (12bits) indicates maximum of 4096 IDs can be generated by one machine in 1ms.
 *
 **/

/* Epoch start time (2022-01-01 00:00:00) */
#define _EPOCH_ 1640966400000ULL
/** Sequence generation mask, here is 4095 (0b111111111111 = 0xfff = 4095) */
#define _SEQUENCE_BITS_ 12
#define _SEQUENCE_MASK_ ((1 << _SEQUENCE_BITS_) - 1)

/** Machine ID, here is 1023 (0b1111111111 = 0x3FF = 1023) */
#define _WORKERID_MAX_ 1023
/** Shift machine ID left by 10 bits */
#define _WORKERID_SHIFT_ 10
/** Shift timestamp left by 22 bits */
#define _TIMESTAMP_SHIFT_ 22

void _cc_snowflake(_cc_snowflake_t *snowflake, int16_t worker_id) {
    _cc_assert(snowflake != NULL);
    if (snowflake == NULL) {
        return;
    }
    
    if (worker_id > _WORKERID_MAX_ || worker_id < 0) {
        worker_id = rand() % _WORKERID_MAX_;
        _cc_logger_error(_T("worker Id can't be greater than %d or less than 0"), _WORKERID_MAX_);
    }
    snowflake->seq = 1;
    snowflake->worker_id = worker_id;
}

_CC_FORCE_INLINE_ uint64_t _timestamp(void) {
    return _cc_timestamp() - _EPOCH_;
}

/** When the number of IDs generated in one millisecond exceeds 4095, the system will wait until the next millisecond to continue generating IDs */
_CC_FORCE_INLINE_ uint64_t _next_millis(_cc_snowflake_t *snowflake) {
    uint64_t timestamp = _timestamp();
    while (timestamp <= snowflake->last) {
        timestamp = _timestamp();
        _cc_sleep(0);
    }
    return timestamp;
}

/**/
uint64_t _cc_snowflake_id(_cc_snowflake_t *snowflake) {
    uint64_t timestamp = _timestamp();
    _cc_assert(snowflake != NULL);
    if (snowflake == NULL) {
        return 0;
    }

    if (timestamp == snowflake->last) {
        /** If sequence increments to 4095, i.e., 4096 % 4095 = 0, get new timestamp */
        snowflake->seq = (snowflake->seq + 1) & _SEQUENCE_MASK_;
        if (snowflake->seq == 0) {
            timestamp = _next_millis(snowflake);
        }
    } else if (snowflake->last > timestamp) {
        _cc_logger_error(_T("Clock moved backwards.  Refusing to generate id for %lld milliseconds"), snowflake->last - timestamp);
        return 0;
    } else {
        snowflake->seq = 0;
    }
    snowflake->last = (long)timestamp;
    /**
     * Return result:
     * (timestamp - twepoch) << _TIMESTAMP_SHIFT_) means subtract initial timestamp from current timestamp, then shift left by corresponding bits
     * (worker_id << _WORKERID_SHIFT_) means shift worker ID left by corresponding bits
     * | is bitwise OR operator, e.g., x | y, result is 0 only when both x and y are 0, otherwise result is 1.
     * Since each part only has meaningful values on corresponding bits, and other bits are 0,
     * performing | operation on each part yields the final concatenated ID
     */
    return (timestamp << _TIMESTAMP_SHIFT_) | ((uint64_t)snowflake->worker_id << _WORKERID_SHIFT_) | snowflake->seq;
}
